### ISSUE TITLE
Keithley_2231A_PyVISA_Examples.py not supported in python 3

### ISSUE THREAD

**Issue by zkoppert** [tektronix/keithley#2]
2to3 output:

RefactoringTool: Refactored Keithley_2231A_PyVISA_Examples.py --- Keithley_2231A_PyVISA_Examples.py (original)
+++ Keithley_2231A_PyVISA_Examples.py (refactored) @@ -17,7 +17,7 @@
# my_PS.flow_control = # only available in PyVisa 1.9 #my_PS.baud_rate = 9600
if getIdStr == 1:- print(my_PS.query("*IDN?"))
+ print((my_PS.query("*IDN?"))) #time.sleep(0.1)
my_PS.write('SYST:REM') #print(my_PS.timeout)
@@ -93,4 +93,4 @@ rm.close
t2 = time.time() # Capture stop time...
-print("{0:.3f} s".format((t2-t1))) +print(("{0:.3f} s".format((t2-t1))))
RefactoringTool: Files that need to be modified: RefactoringTool: Keithley_2231A_PyVISA_Examples.py

**Comment by zkoppert** [comment]
@nlynchjo transferred from previous repo to here.

**Comment by jbrown1234** [comment]
A recent revision of the code addresses this, however, builds are failing and the push is not taking. I will work with internal team members to determine the source of the failure and we will move forward with the update then. Thank you for bringing this to our attention.
