### ISSUE TITLE
What kind of license is the DMM6500 driver

### ISSUE THREAD

**Issue by CodeF00l** [tektronix/keithley#27]
It is unclear to me which license the Keithley DMM6500_VISA_Driver.py currently has.

This page has the Tektronix license while this other one https://github.com/jbrown1234/Keithley_DMM6500_Drivers has a GPL3 license.

Can someone clear this up?

**Comment by Brad-O** [comment]
Good question, the DMM6500 Driver found in this repo is licensed under the [Tektronix Sample License](https://github.com/tektronix/keithley/blob/master/LICENSE). @jbrown1234 wrote the driver and chose to use the GPL3 license in his own repo, while also posting it here under the Tek Sample license.

**Comment by jbrown1234** [comment]
Good catch & call out - thanks to you both! I'm planning on replacing this driver with something with more functionality and moving to make it more Pythonic. Don't have a definitive timeframe.... coming soon-ish. :) Further feedback on the existing one is appreciated.
