### ISSUE TITLE
README Contributing section should specify which branch to pull request to.

### ISSUE THREAD

**Issue by zkoppert** [tektronix/keithley#3]
**Describe the bug**
README Contributing section should specify which branch to pull request to.

**To Reproduce**
1. View README
2. Go to Contributing Section
3. Notice that users don't know which branch to pull request to (master or dev)

**Expected behavior**
README Contributing section should specify which branch to pull request to. (master or dev)

** Environment (please complete as much as possible):**
N/A

**Additional context**
N/A

**Comment by Brad-O** [comment]
Resolved into master with 1989fef0798a21b642d8beb463c181932682907c
