### ISSUE TITLE
[REQ] API documentation for display.create() and related functions

### ISSUE THREAD

**Issue by mihtjel** [tektronix/keithley#47]
I've been trying to reverse engineer what the various OBJ_* types take as parameters - giving a huge number of parameters to get the DMM to tell me what the minimum and maximum number of parameters is, and then giving it "wrong" data for each of them to get the name of the parameter. As well as looking at the various apps available here and on the Keithley website. But .. this seems like a really inefficient way to use the API.

So, could you be convinced to post just a simple listing of the various functions and parameters? I realize that complete documentation would take a while, but anything is better than having to guess 100% of the time ;-)

Thanks!

**Comment by Brad-O** [comment]
Thanks @mihtjel, this is under review with the team.

**Comment by mihtjel** [comment]
Any updates on this? I figure it would be a good follow-up to the July 19th app note on boosting test automation.

**Comment by Brad-O** [comment]
I'm glad to say I do have an update! We will be adding what API documentation we have to this Repo. I am currently formatting it, fixing some major errors, and scrubbing for confidentiality. I expect to push the commit mid next week at the latest.

**Comment by mihtjel** [comment]
This is great news! 👍I look forward to getting the work I've already done checked against the docs! 😁

**Comment by Brad-O** [comment]
The TTI Display API for Keithley touchscreen instruments has been added with commit 99b15195ec64cedfd44aef4ed4db83bdbf94ee6c 

It is available at https://github.com/tektronix/keithley/tree/main/TTI_Apps/TTI_Display_API
