### ISSUE TITLE
[BUG] 00_Stream_Data_from_DMM6500/Stream_DMM6500.py  -> "Error 1151 Command requires installation of accessory card"

### ISSUE THREAD

**Issue by aewallin** [tektronix/keithley#54]
This form should only be used for issues related to this repo. For technical assistance or advice, visit [tek.com](http://www.tek.com).

I am trying the example: 00_Stream_Data_from_DMM6500/Stream_DMM6500.py
Ethernet communication seems to work, the example runs and prints out "functions loaded"

I then get on the screen of the DMM6500 "Error 1151 Command requires installation of accessory card"
I don't have any accessory cards installed - I was hoping this example could capture voltage/current readings using the standard front or back connectors.

**To Reproduce**
1. run Stream_DMM6500.py  , only modification I made is to change the ip_address
4. See error 1151

**Expected behavior**
example runs until end and stores voltage-readings in txt-file on computer

** Environment (please complete as much as possible):**
- Instrument: DMM6500
- Firmware version: 1.7.12b
- Communication: LAN
- Command set: TSP

**Additional context**

**Comment by Brad-O** [comment]
Thank you @aewallin, @jbrown1234 can you take a look at this?

**Comment by jbrown1234** [comment]
Hi @aewallin!

This example can be modified to bypass the dependency on the accessory card responsible for the TSP-Link line triggering dependency. 

In the initial script file (functions_V3.lua), lines 6 & 7 configure the accessory card hardware for a self triggering setup, then line 25 holds the dependency to monitor the TSP-Link line for the trigger signal. 

For self triggering using the EXT Input and External Output that comes standard on the rear panel with the DMM6500, first you'll provide a connection between these two terminals. Then lines 6 & 7 can be replaced with the following: 

```
trigger.extout.stimulus = trigger.EVENT_NOTIFY1
trigger.extin.edge = trigger.EDGE_FALLING
```

Additionally, line 25 would be updated as follows:

```
trigger.model.setblock(2, trigger.BLOCK_WAIT, **trigger.EVENT_EXTERNAL)**
```

I'll upload the modified script file that I just used with these change recommendations and have confirmed it works.

Regards

jbrown1234
