### ISSUE TITLE
load_script_file_onto_keithley_instrument function is not exist.[BUG]

### ISSUE THREAD

**Issue by oz-piita** [tektronix/keithley#58]
Instrument_Control_Example_Send_a_Script.go has no function load_script_file_onto_keithley_instrument().
This code won't work.

**Comment by Brad-O** [comment]
Instrument_Examples/General/Instructables/Get_Started_with_Instr_Control_Go/Instrument_Control_Example_Send_a_Script.go

Ah, thanks! The other Go examples have that function, but ironically it was left out of the example with "send a script" in the title. I will add that function later this week.

**Comment by Brad-O** [comment]
Fixed in d2ec6fa726d6ae814770b84eaa3c4f40b0383aa3
